config/routes.rb
Rails.application.routes.draw do
  get 'settings' => 'organizations#edit', as: :settings

  match '/tableau/org/:organization_id/upload' => 'tableau#handle_upload', via: [:post, :put]
  get '/tableau/current_org/:image' => 'tableau#current_org_image'
  get '/tableau/any_org/:image' => 'tableau#any_org_image'

  resource :admin do
    resources :organizations, controller: 'admin/organizations' do
      post :change_to, to: 'admin/organizations#change_to', as: :change_to, on: :member
    end

    match '/user_merge' => 'admin/organizations#user_merge', via: [:get, :post]

    root 'admin/organizations#index', as: :admin_root
  end

  get '/org/:organization_uuid/srv/:survey_uuid' => 'splashes#show', as: :anonymous_survey
  get '/org/:organization_uuid/srv/:survey_uuid/create_anonymous_survey' => 'splashes#create_anonymous_survey', as: :create_anonymous_survey

  resources :claim_attachments

  resources :organizations do
    get :self_signup, on: :member, to: 'organizations#self_signup'
    get :profile, on: :member, to: 'users#profile'
    get :setup, on: :member, to: 'organizations#setup'
    get :manage_org_admins, on: :member, to: 'organizations#manage_org_admins'

    match '/editor/(:field)' => 'organizations#editor', via: [:get, :post], as: :editor

    resources :notes, controller: 'organizations/notes', only: [:index]
    resources :offers, controller: 'organizations/offers'

    resources :claims, controller: 'organizations/claims' do
      match :import, via: [:get, :post], on: :collection
      post :reimburse, on: :member
      get :proof, on: :member
      post :bulk, on: :collection
      get :historical, on: :collection

      match :export, on: :collection, via: [:get, :post]
      match :export_agg, on: :collection, via: [:get, :post]

      resources :notes, controller: 'organizations/notes'
    end
    resources :people, controller: 'organizations/people', path: "employees" do
      match :deposit, via: [:get, :post], on: :collection
      match :upload, via: [:get, :post], on: :collection
      match :import, via: [:get, :post], on: :collection
      match :invitations, on: :collection, via: [:get, :post]
      post :reset_password, on: :member
      post :send_invite, on: :member
    end
    resources :funds, controller: 'organizations/funds'
    resources :products, controller: 'organizations/products', path: 'specific_products' do
      match :upload, to: 'organizations/products#upload', on: :collection, via: [:get, :post]
    end

    resources :reimbursement_rules, controller: 'organizations/reimbursement_rules', path: 'benefits_database' do
      post :import, on: :collection
    end

    resources :pages, controller: 'organizations/pages'

    resources :benefit_categories, only: [:edit, :show, :update, :destroy], controller: 'organizations/benefit_categories'
    resources :benefit_programs, controller: 'organizations/benefit_programs' do
      member do
        get :program_funds
        get :program_claims
      end

      resources :benefit_categories, controller: 'organizations/benefit_categories' do
        collection do
          post :upload
        end
      end
    end

    resources :surveys, controller:'organizations/surveys' do
      get :overview, on: :member
      get :preview, on: :member
      get :search_questions, on: :member
      get :help, on: :member
      post :upload, on: :member
      post :import, on: :member
      post :import_report_questions, on: :member
      post :reset, on: :member
      post :deploy_changes, on: :member
      get :clone, on: :member
      post :clone, on: :member
      get :move_to, on: :member
      post :move_to, on: :member
      post :push_changes_to, on: :member
      match 'report' => 'organizations/surveys#report', as: :report, via: [:get, :post, :put], on: :member

      get :remove, on: :member

      match 'templates' => 'organizations/surveys#templates', via:[:get,:post]
      post :restore_template, on: :member

      resources :messages, controller: 'organizations/messages' do
        post :deliver, on: :member
      end

      resources :sections,controller:'organizations/sections' do
        resources :groups,controller:'organizations/groups' do
          resources :questions,controller:'organizations/questions'
        end
      end

      resources :rules, controller: 'organizations/rules'
      resources :questions, controller: 'organizations/questions'
      resources :users, controller: 'organizations/users' do
        post :import, on: :collection
        post :import_historical_records, on: :collection
        post :attach_meta_data, on: :collection
        post :invite, on: :collection
        post :reset, on: :collection
        post :download_data, on: :collection
        post :download_results, on: :collection
        post :make_admin, on: :member
        post :rerun_calculations, on: :collection
        post :toggle_survey_is_valid, on: :member
        post :allowed_to_submit_answers, on: :member
        post :add_from_organization, on: :collection
        post :toggle_open_and_closed_surveys, on: :collection, via: [:post]
        post :share_spreadsheet, on: :collection
        get :compare, on: :collection

        post :run_results, on: :member
        post :reinvite, on: :member
      end
    end
  end

  get 'footprint' => 'surveys#footprint', as: :footprint
  get 'no_footprint_yet' => 'surveys#no_footprint', as: :no_footprint
  resources :surveys do
    get :report
    get :data
    get :faq
    get :complete
    get :start
    get :profile, on: :member, to: 'users#profile'

    resources :sections, controller:'surveys/sections' do
      get :start, to: 'surveys/sections#start'
      get :complete
      get :info

      resources :groups, controller: 'surveys/groups' do
        get :next, on: :member
        get :prev, on: :member
        resources :questions, controller: 'surveys/questions'
      end
    end

    resources :questions, controller: 'surveys/questions' do
      post :answer, on: :member
    end

    get 'report/results' => 'surveys/results#index'
    get 'report/histogram' => 'surveys/results#histogram'

    get 'finish' => 'surveys#finish'
  end

  resources :benefit_categories, path: 'explore', only: [:index]
  resources :benefit_categories
  resources :programs, path: 'programs' do
    match :submit_claim, on: :collection, via: [:get, :post]
  end

  resources :products, path: 'benefits' do
    get 'about', on: :collection
    get 'focus_area', on: :collection
    get 'category', on: :collection
    match 'saved', on: :collection, path: 'wishlist', via: [:get, :post]

    resources :claims, only: [:new]
  end

  resources :claims do
    member do
      match 'change_benefit_category' => 'claims#change_benefit_category', via: [:get, :post]
    end
  end

  get '/pages/:id' => 'pages#show', as: :page
  get '/offers' => 'pages#offers', as: :offers

  match 'profile' => 'users#profile', via: [:get, :post]
  match 'login' => 'users#login',via:[:get,:post], as: :login
  match 'logout' => 'users#logout', via: [:get, :post, :delete]
  match 'password' => 'users#password', via:[:get,:post]
  match 'reset_password/:user_uuid' => 'users#reset_password', via:[:get], as: :reset_password

  match 'profile' => 'users#update', via: :put
  match 'invite/:user_uuid' => 'users#login_with_token', via: [:get], as: :login_with_token
  match 'relogin' => 'users#relogin_super_admin', via: [:get], as: :relogin_super_admin
  match ':organization_name/invites/:employee_invite_uuid' => 'organizations#employee_invitation', via: [:get, :post], as: :employee_invitation

  match 'create-new-org' => 'users#register', via: [:get, :post], as: :register

  match "/delayed_job" => DelayedJobWeb, :anchor => false, via: [:get, :post]


  get '/saml/:idp/sso' => 'saml#sso'
  match '/saml/:idp/acs' => 'saml#acs', via: [:get, :post]
  get '/saml/:idp/metadata' => 'saml#metadata'
  get '/saml/:idp/logout' => 'saml#logout'

  match '/:signup_slug' => 'signup_slug#show', via: [:get, :post], as: :signup_slug
  match '/:signup_slug/continue_signup' => 'signup_slug#continue_signup', via: [:get, :post], as: :continue_signup


  root 'organizations#dashboard'
end

app/controllers/admin/organizations_controller.rb
class Admin::OrganizationsController < AdminController
  def index
  end

  def new
  end

  def create
    organization = Organization.new(params_for(Organization))
    organization.save
    session[:admin_organization_id] = organization.id
    flash[:notice] = "Organization added"

    redirect_to edit_organization_path(organization)
  end

  def change_to
    organization = Organization.find(params[:id])
    session[:admin_organization_id] = organization.id

    redirect_to organization_path(organization)
  end

  def user_merge
    if request.post?
      emails = []
      params[:from].each_with_index do |email, index|
        next if email.blank?

        user_from = User.find_by(email: params[:from][index])
        user_to = User.find_by(email: params[:to][index])

        Claim.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        ClaimAttachment.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        Fund.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        HistoricalRecord.where(user_id: user_from.id).update_all(user_id: user_to.id)
        Survey.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        Question.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        Result.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        Note.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)
        UserField.where(user_id: user_from.id).update_all(user_id: user_to.id, organization_id: user_to.organization_id)

        user_from.update_column(:email, "#{user_from.email}.bak")
      end

      render text: "All done!", layout: false
    end
  end
end

app/controllers/organizations/benefit_categories_controller.rb
class Organizations::BenefitCategoriesController < ApplicationController
  def edit
  end

  def update
    c = _organization.benefit_categories.find(params[:id])
    c.update(params_for(BenefitCategory))
    redirect_to :back
  end

  def index
    @benefit_category = _organization.benefit_categories.order(id:params[:benefit_category][:id])
    respond_todo |format|
      format.html
      format.csv { send_data @benefit_category.to_csv }    
  end

  def create
    benefit_category = BenefitCategory.create(params_for(BenefitCategory).merge(
      organization_id:_organization.id
    ))
    _benefit_program.benefit_categories << benefit_category
    redirect_to [_organization, _benefit_program]
  end

  def destroy
    _organization.benefit_categories.find(params[:id]).destroy
    redirect_to :back
  end

  def upload
    rows = params[:upload][:file].read.split("\n").map do |row|
      next if row =~ /percent to reimburse/i
      next if row =~ /^category/i
      next if line.to_s.strip.blank?


      row = row.strip.split(",").map(&:strip)
      {
        name: row[0],
        focus_area: row[1],
        product_type: row[2],
        percent_to_reimburse: row[3],
        description: row[4],
        focus_area_description: row[5],
        product_type_description: row[6],
        program_name: row[7],
        eligibility_description: row[8],
        description_of_exclusions: row[9],
        benefit_category_image_url: row[10],
      }
    end.compact

    rows.each do |row|
      benefit_category = _organization.benefit_categories.where(
        # organization_id: _organization.id,
        # benefit_program_id: _benefit_program.id,
        name: row[:name],
        focus_area: row[:focus_area],
        product_type: row[:product_type]
      ).first_or_create

      _benefit_program.benefit_categories << benefit_category unless _benefit_program.benefit_categories.include?(benefit_category)

      benefit_category.update(row.except(:program_name))
    end

    redirect_to [_organization, _benefit_program]
  end
end

app/controllers/organizations/benefit_programs_controller.rb
class Organizations::BenefitProgramsController < ApplicationController
  def create
    redirect_to [_organization, _organization.benefit_programs.create(params_for(BenefitProgram))]
  end

  def update
    p = _organization.benefit_programs.find(params[:id])
    p.update(params_for(BenefitProgram))
    redirect_to [p.organization, p]
  end
end

app/controllers/organizations/funds_controller.rb
class Organizations::FundsController < OrganizationsController
  def create
    if params[:user_id]
      user = _organization.users.find(params[:user_id])
      fund = user.funds.new(params_for(Fund))

      # if params[:fund] && params[:fund][:program_id]
      #   fund.program = _organization.programs.find(params[:fund][:program_id])
      # end

      if params[:benefit_program] && params[:benefit_program][:name].present?
        @benefit_program = _organization.benefit_programs.where(name: params[:benefit_program][:name]).first
      end

      fund.benefit_program = @benefit_program
      fund.organization = _organization
      fund.save
    end

    redirect_to :back
  end

  def destroy
    _organization.funds.find(params[:id]).destroy
    redirect_to :back
  end
end

app/controllers/organizations/groups_controller.rb
class Organizations::GroupsController < OrganizationsController
  layout 'organizations/surveys'

  def new
  end

  def update
    _group.update(params_for(Group))
    redirect_to :back
  end

  def create
    group = _section.groups.new(params_for(Group))
    group.organization=_organization
    group.survey=_survey
    group.save
    redirect_to [_organization, _survey, _section, group]
  end

  def show
  end

  def destroy
    _survey.groups.where(master_group_uuid: _group.uuid).destroy_all
  end
end

app/controllers/organizations/messages_controller.rb
class Organizations::MessagesController < OrganizationsController
  layout 'application'

  def show
  end

  def create
    message = _survey.messages.new(params_for(Message))
    message.organization = _organization

    if message.save
      flash[:notice] = "Message saved"
      redirect_to [_organization, _survey, message]
      return
    else
      redirct_to :back
    end
  end

  def update
    _message.update(params_for(Message))
    flash[:notice] = "Message updated"
    redirect_to :back
  end

  def deliver
    message = _survey.messages.find(params[:id])

    if message
      case params[:deliver_to]
      when 'everyone'
        surveys = _survey.surveys.all
      when 'in_progress'
        surveys = _survey.surveys.in_progress
      when 'not_yet_started'
        surveys = _survey.surveys.not_yet_started
      when 'complete'
        surveys = _survey.surveys.complete
      when 'invalid'
        surveys = _survey.surveys.invalid
      end

      surveys.for_active_employees.each do |survey|
        survey.delay.send_message_to_user(message)
      end

      message.update(deliver_to: params[:deliver_to], delivered_at: Time.now)

      flash[:notice] = "Message queued for delivery"
    end

    redirect_to :back
  end

  def destroy
    _message.destroy
    redirect_to :back
  end
end

app/controllers/organizations/notes_controller.rb
class Organizations::NotesController < OrganizationsController
  def create
    @note = _organization.notes.new(params_for(Note))
    @note.user = _claim.user
    @note.claim = _claim
    @note.author = _user

    @note.save
    redirect_to :back
  end
end

app/controllers/organizations/offers_controller.rb
class Organizations::OffersController < ApplicationController
  def create
    offer = _organization.offers.new(params_for(Offer))
    offer.save
    redirect_to organization_offers_path(_organization)
  end

  def update
    _offer.update(params_for(Offer))
    redirect_to organization_offers_path(_organization)
  end

  def destroy
    _offer.destroy
    redirect_to organization_offers_path(_organization)
  end
end

app/controllers/organizations/pages_controller.rb
class Organizations::PagesController < OrganizationsController
  def create
    @page = _organization.pages.new(params_for(Page))
    @page.save

    redirect_to [_organization, @page]
  end

  def show
  end

  def update
    _page.update(params_for(Page))
    redirect_to [_organization, _page]
  end

  def destroy
    _page.destroy
    redirect_to organization_pages_path(_organization)
  end
end

app/controllers/organizations/programs_controller.rb
class Organizations::ProgramsController < OrganizationsController
  def index
  end

  def show
  end

  def new
  end

  def create
    redirect_to [_organization, _organization.programs.create(params_for(Program))]
  end

  def update
    program = _organization.programs.find(params[:id])
    program.update(params_for(Program))
    redirect_to [_organization, program]
  end

  def destroy
    _program.destroy
    redirect_to organization_programs_path(_organization)
  end
end

app/controllers/organizations/rules_controller.rb
class Organizations::RulesController < OrganizationsController
  def create
    answer_from = _survey.questions.where(text: params[:rule][:answer_from]).first
    group_id = params[:rule][:group_id]
    question_id = params[:rule][:question_id]

    rule = _survey.rules.new(params_for(Rule))
    rule.organization = _organization
    rule.answer_from = answer_from
    rule.group_id = group_id
    rule.question_id = question_id
    rule.save

    redirect_to :back
  end

  def update
    _rule.update(params_for(Rule))
    redirect_to :back
  end

  def destroy
    _rule.destroy
    redirect_to :back
  end
end

app/views/organizations/reimbursement_rules/_reimbursement_rule.html.erb
<tr>
  <td>
    <% if reimbursement_rule.program.present? %>
      <%= link_to [_organization, reimbursement_rule.program] do %>
        <%= reimbursement_rule.program.name %>
      <% end %>
    <% end %>
  </td>
  <td>
    <%= reimbursement_rule.focus_area.present? ? reimbursement_rule.focus_area : '--' %>
  </td>
  <td>
    <%= reimbursement_rule.category_name.present? ? reimbursement_rule.category_name : '--' %>
  </td>
  <td>
    <%= number_to_percentage reimbursement_rule.percentage.to_f, precision:0 %>
  </td>
  <td style="">
    <%= link_to [:edit, reimbursement_rule.organization, reimbursement_rule] do %>
      <i class=""></i> Edit
    <% end %>
  </td>
  <td style="">
    <%= link_to [reimbursement_rule.organization, reimbursement_rule], method: :delete, data: {confirm:"Are you sure?"} do %>
      <i class=""></i>
      Remove
    <% end %>
  </td>
</tr>

app/views/organizations/reimbursement_rules/_subheader.html.erb
<%= content_for :subheader do  %>
  <div class="nav">

    <div class="">
      <%= link_to "Programs", organization_programs_path(_organization) %>
    </div>
    <div>
      <%= link_to new_organization_program_path(_organization) do %>
        <i class=""></i> Add
      <% end %>
    </div>
    <div>
      <%= link_to "Benefits", organization_reimbursement_rules_path %>
    </div>
    <div>
      <%= link_to new_organization_reimbursement_rule_path(_organization) do %>
        <i class=""></i>
        Add
      <% end %>
    </div>
    <div>
      <%= link_to organization_products_path(_organization) do %>
        Specific Products
      <% end %>
    </div>
    <div>
      <%= link_to new_organization_product_path(_organization) do %>
        <i class=""></i>
        Add
      <% end %>

    </div>
    <div class="subheader-form" style="">
      <form class="" action="" method="get">
        <input type="text" name="filter" value="<%= params[:filter] %>" placeholder="Find a product">
        <button>Go</button>
      </form>
    </div>
  </div>
<% end %>

app/views/organizations/reimbursement_rules/edit.html.erb
<%= render 'subheader' %>

<div class="">
  <div class="">
    <div class="">
      <h3>Edit Reimbursement Rule</h3>
      <div class="">
        <%= form_for [_reimbursement_rule.organization, _reimbursement_rule] do |f| %>
          <div class="">
            <label>Program</label>
            <%= f.select :program_id, (_organization.programs.map { |program| [program.name, program.id]}), prompt: "Choose" %>
            
          </div>

          <div class="">
            <label>Category </label>
            <%= f.text_field :focus_area %>
          </div>
          <div class="">
            <label>Category Description</label>
            <%= f.text_field :focus_area_description %>
          </div>

          <div class="">
            <label>Product Type</label>
            <%= f.text_field :category_name %>
          </div>
          <div class="">
            <label>Product Type Description </label>
            <%= f.text_field :category_name_description %>
          </div>

          <div class="">
            <label>Amount to Reimburse</label>
            <%= f.text_field :percentage %>
          </div>

          <div class="">
            <label>Focus Area Image URL Address</label>
            <%= f.text_field :image_url %>
          </div>

          <div class="">
            <button>Save</button>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/organizations/reimbursement_rules/index.html.erb
<%= render 'subheader' %>

<div class="">
  <b>Reimbursement Rules</b>
  contain category and product type information, including descriptions and allowable reimbursement amounts.
</div>

<table>
  <thead>
  <tr>
    <th>Program</th>
    <th>Category</th>
    <th>Product Type</th>
    <th colspan="3">Allowable Reimbursement Amount</th>
  </tr>
  </thead>
  <tbody>
  <% reimbursement_rules = _organization.reimbursement_rules  %>
  <%= render reimbursement_rules %>
  <%= empty_table_rows(4) if reimbursement_rules.empty? %>
  </tbody>
</table>

app/views/organizations/reimbursement_rules/new.html.erb
<%= render 'subheader' %>

<div class="" style="">
  <div class="">
    <div class="">
      <h3>Add New Rule</h3>
      <div class="">
        <%= form_for :reimbursement_rule, url: organization_reimbursement_rules_path(_organization) do |f| %>
          <div class="">
            <label>Category </label>
            <%= f.text_field :focus_area %>
          </div>
          <div class="">
            <label>Category Description</label>
            <%= f.text_field :focus_area_description %>
          </div>
          <div class="">
            <label>Product Type</label>
            <%= f.text_field :category_name %>
          </div>
          <div class="">
            <label>Product Type Description </label>
            <%= f.text_field :category_name_description %>
          </div>
          <div class="">
            <label>Amount to Reimburse</label>
            <%= f.text_field :percentage %>
          </div>
          <div class="">
            <label>Focus Area Image URL Address</label>
            <%= f.text_field :image_url, placeholder: "http://..." %>
          </div>

          <div class="">
            <button>Add Rule</button>
          </div>
        <% end %>
      </div>
    </div>
    <div class="">
      <h3>Upload CSV File</h3>
      Please include the following fields. You may include headers in uploaded file.
      <%= link_to "Download sample file", "/upload_reimbursement_rules.csv", target: "_blank" %>
      <pre style="">Category, Product Type, Kind, %Reimburse, Category Description, Product Type Description, Program Name</pre>

      <%= form_for :upload, url: import_organization_reimbursement_rules_path(_organization) do |f| %>
        <%= f.file_field :file %>
        <button>Upload</button>
      <% end %>

      <small>
        <i>
          *A new program will be created if it is present in the CSV file and not in the database already.
          It cab be configures in the <%= link_to "programs", organization_programs_path(_organization) %> section.
        </i>
      </small>
    </div>
  </div>
</div>